/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	import testSuite.TestSuite;
	//import testSuite.tests.TestPlayer;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		//private var testSuite_tests_TestPlayer_obj:testSuite.tests.TestPlayer;
		private var testSuite_TestSuite_obj:testSuite.TestSuite;
	}
}